hw completed
maksar24/nodejs-homework-rest-api pull request #2
Opened 2021-11-30 16:55 UTC by maksar24

2021-11-30 21:19 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://maksar24:2eQeGkCrBQYpkWrh@cluster0.u5p3g.mongodb.net/db-contacts?retryWrites=true&w=majority
удалить с гита и добавить файл в gitignore

2021-11-30 21:23 UTC, maksar24 commented on .env
> +DB_HOST=mongodb+srv://maksar24:2eQeGkCrBQYpkWrh@cluster0.u5p3g.mongodb.net/db-contacts?retryWrites=true&w=majority
Окей....Я просто не добавил его изначально в .gitignore, чтобы можно было моей базой воспользоваться при проверке

2021-11-30 21:24 UTC, KirillKulakow commented on controllers/contacts/updateContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true })
https://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate
не вижу там такой опции как new, лучше использовать returnDocument

2021-11-30 21:25 UTC, KirillKulakow commented on controllers/contacts/updateStatusContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, { favorite }, { new: true })
так же

2021-11-30 21:26 UTC, KirillKulakow commented on .env
> +DB_HOST=mongodb+srv://maksar24:2eQeGkCrBQYpkWrh@cluster0.u5p3g.mongodb.net/db-contacts?retryWrites=true&w=majority
не переживай - если что я на своей потестирую

2021-11-30 21:26 UTC, KirillKulakow requested changes
Need fix

2021-11-30 21:28 UTC, maksar24 commented on controllers/contacts/updateContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true })
это преподаватель просто на занятии показал так

2021-11-30 21:54 UTC, maksar24 commented on controllers/contacts/updateContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true })
new: bool - if true, return the modified document rather than the original. defaults to false (changed in 4.0)

2021-11-30 21:54 UTC, maksar24 commented on controllers/contacts/updateContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true })
можно пожалуйста оставить { new: true }, если я нашел это в доках?...

2021-12-01 20:15 UTC, KirillKulakow commented on controllers/contacts/updateContact.js
> +  const contact = await Contact.findByIdAndUpdate(contactId, req.body, { new: true })
ок, там есть промежуточный обработчик при помощи которого можно использовать данную опцию

2021-12-01 20:15 UTC, KirillKulakow approved these changes

2021-12-01 20:26 UTC, merged