finished without last of extra tasks
maksar24/nodejs-homework-rest-api pull request #3
Opened 2021-12-09 23:19 UTC by maksar24

Пожалуйста проверьте, а последнее задание по фильтрации я сделаю позже (p.s. после работы)))

2021-12-10 19:35 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit
лучше перед этой строкой делать проверку на page и limit чтобы были числами - если нет вернуть badRequest

2021-12-10 19:37 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  if (validationId === false) {
лучше так в дальнейшем не использовать проверку - лучше писать !validationId

2021-12-10 19:38 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById))
контакт по ид может получить любой юзер?

2021-12-10 19:38 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById))
даже не авторизированный?

2021-12-10 19:38 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.delete('/:contactId', ctrlWrapper(ctrl.removeContact))
тот же вопрос что и по поиску по ид

2021-12-10 19:38 UTC, KirillKulakow requested changes
Need refactor

2021-12-10 20:03 UTC, maksar24 commented on routes/api/contacts.js
>  router.get('/:contactId', ctrlWrapper(ctrl.getContactById))
добавил проверку токена

2021-12-10 20:03 UTC, maksar24 commented on routes/api/contacts.js
>  router.delete('/:contactId', ctrlWrapper(ctrl.removeContact))
добавил проверку токена

2021-12-11 12:42 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const skip = (page - 1) * limit
не поправил

2021-12-11 12:42 UTC, KirillKulakow commented on controllers/users/updateSubscription.js
> +  console.log(req.body)
удалить

2021-12-11 12:43 UTC, KirillKulakow requested changes
Need refactor

2021-12-14 19:29 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +      message: 'Bad request'
плохой вариант - у тебя же есть http errors
а так ты отдаешь статус 200 - success с текстом bad request

2021-12-14 19:29 UTC, KirillKulakow requested changes
Need fix

2021-12-14 19:42 UTC, KirillKulakow approved these changes

2021-12-14 19:49 UTC, merged