Hw05 avatars
maksar24/nodejs-homework-rest-api pull request #4
Opened 2021-12-17 16:04 UTC by maksar24

Основу сделал. Но при попытках писать тесты к контролерам столкнулся с проблемой, которую не смог решить(

2021-12-17 21:41 UTC, KirillKulakow commented on controllers/users/register.js
> +  const avatarURL = gravatar.url(email)
добавить протокол https

2021-12-17 21:41 UTC, KirillKulakow commented on controllers/users/register.js
> +  const avatarURL = gravatar.url(email)
или http

2021-12-17 21:41 UTC, KirillKulakow commented on controllers/users/register.js
>    newUser.save()
save асинхронная функция

2021-12-17 21:53 UTC, maksar24 commented on controllers/users/register.js
>    newUser.save()
добавить awaitюююютак же?

2021-12-17 22:04 UTC, maksar24 commented on controllers/users/register.js
> +  const avatarURL = gravatar.url(email)
типо так const avatarURL = gravatar.url(`https//${email}`)
?

2021-12-18 15:12 UTC, maksar24 commented on controllers/users/register.js
> +  const avatarURL = gravatar.url(email)
добавил

2021-12-18 15:12 UTC, maksar24 commented on controllers/users/register.js
>    newUser.save()
добавил оператор await перед save

2021-12-18 21:03 UTC, KirillKulakow commented on controllers/users/login.test.js
> +const express = require('express')
тесты пока не засчитаны - потом нужно будет поправить
1) нужно добавить подключение к тестовой бд
2) нужно после проведения теста закрывать соединение
3) при логине тебе нужно добавлять имейл и пароль в body

2021-12-18 21:03 UTC, KirillKulakow commented on controllers/users/register.test.js
> +const express = require('express')
тесты пока не засчитаны - потом нужно будет поправить

2021-12-18 21:04 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
здесь было бы неплохо добавить проверку на тип файла - чтобы загружать только изображения

2021-12-18 21:08 UTC, KirillKulakow requested changes
Need some adds

2021-12-19 21:10 UTC, maksar24 commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
добавил

2021-12-20 19:46 UTC, KirillKulakow approved these changes

2021-12-20 21:25 UTC, merged